[package]
name = "chiffonist"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde_yaml = "0.9.34"
tabwriter = "1.4.1"
